// WebGL Water - pool walls & floor (Unity 6 / URP port)
// The pool mesh is generated by the scene builder already in world coordinates:
// floor at y = -1, walls rising to y = 2/12, spanning x,z in [-1, 1].
// Keeps the original analytic look (GetWallColor: refracted-light diffuse, projected
// caustics, rim shadow) but is now a proper URP forward pass, so it also RECEIVES
// real shadows cast by interactable objects from the scene's directional light.
Shader "WebGLWater/PoolWall"
{
    Properties
    {
        [Enum(UnityEngine.Rendering.CullMode)] _Cull ("Cull", Float) = 2 // Back
        _TilesTiling ("Tiles Tiling", Vector) = (1,1,0,0)
        [Toggle(_AUTOTILE)] _AutoTileByFace ("Auto Tile By Face Size", Float) = 0
        [Toggle(_USECUSTOMTILES)] _UseCustomTiles ("Use Custom Tiles Texture", Float) = 0
        _BaseMap ("Custom Tiles", 2D) = "white" {}
        [Normal] _BumpMap ("Normal Map", 2D) = "bump" {}
        _BumpScale ("Normal Scale", Float) = 1
        _ObjectShadowStrength ("Object Shadow Strength", Range(0,1)) = 0.6
        // Matches WaterReceiver's caustic controls. Default 2 reproduces the legacy baked
        // strength, so existing pools look unchanged until tuned (WaterReceiver defaults to 4,
        // but the pool's caustic term also carries refracted diffuse + rim occlusion, so the
        // two strength values are not directly comparable).
        _CausticStrength ("Caustic Strength", Range(0,8)) = 2
        _CausticTint ("Caustic Tint", Color) = (1,1,1,1)
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "Queue"="Geometry" "RenderPipeline"="UniversalPipeline" }
        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode"="UniversalForward" }
            Cull [_Cull]
            ZWrite On
            ZTest LEqual

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile_fragment _ _SHADOWS_SOFT
            #pragma shader_feature_local _USECUSTOMTILES
            #pragma shader_feature_local _AUTOTILE

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            // Analytic helpers (GetWallColor etc). Uses legacy tex2D/sampler2D, which
            // resolve via the auto-included HLSLSupport in URP HLSLPROGRAM blocks.
            #include "WaterCommon.hlsl"
            #include "WaterFog.hlsl"
            #include "WaterVolume.hlsl"

            #define UNDERWATER_WALL_BOOST 1.2 // walls read a touch brighter than the surface underwater

            float _ObjectShadowStrength;
            sampler2D _BaseMap;   // optional per-material tiles albedo (used when _USECUSTOMTILES is on)
            sampler2D _BumpMap;   // pool-wall normal map (defaults flat, so untouched materials are unchanged)
            float4 _TilesTiling;  // xy = tile repeat across the pool faces
            float _BumpScale;
            float _CausticStrength; // per-material caustic gain (see GetWallShadeSplit); default 2 = legacy
            float4 _CausticTint;    // per-material caustic colour, applied like WaterReceiver

            struct appdata { float4 vertex : POSITION; };
            struct v2f
            {
                float4 pos      : SV_POSITION;
                float3 position : TEXCOORD0; // POOL space, for the analytic wall look
                float3 worldPos : TEXCOORD1; // world space, for shadows + fog
            };

            v2f vert(appdata v)
            {
                v2f o;
                float3 poolPos = v.vertex.xyz;          // pool mesh authored in [-1,1]
                float3 worldPos = PoolToWorld(poolPos); // placed by the volume frame
                o.position = poolPos;
                o.worldPos = worldPos;
                o.pos = TransformWorldToHClip(worldPos);
                return o;
            }

            half4 frag(v2f i) : SV_Target
            {
                // Per-material tiles + tiling + normal map on the wall faces, reusing the shared
                // analytic shading (AO / caustics / rim). Defaults reproduce the old look exactly:
                // global _Tiles, tiling (1,1), flat normal.
                float2 wallUV; float3 faceN, wallT, wallB;
                WallSurface(i.position, wallUV, faceN, wallT, wallB);
                // Auto Tile By Face Size: scale each face's UV by its WORLD size along the U/V
                // axes (from the volume extent), so tiles keep an even dens